site_name: baizice
site_url: https://blog.baizice.top # 站点链接
site_author: baizice
repo_url: https://github.com/baizice/baizice.github.io/
repo_name: baizice~
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/20260127_031604.svg # 页面左上角徽标
  icon:
    repo: fontawesome/brands/git
  favicon: assets/20260127_031604.svg # 网页的图标
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)" # 系统主题
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view    
    - content.code.copy # Code Blocks 代码复制按钮
    - content.code.select # Code Blocks 代码选择按钮
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    - navigation.tabs.sticky # 滚动时隐藏顶部nav，需要配合navigation.tabs使用
    - navigation.top # 开启一键回到页面顶部按钮
    - header.autohide # 向下滚动时自动隐藏header
    - navigation.footer # 开启底部上一篇/下一篇导航
    - search.highlight # 搜索栏内容高亮
    - search.share # 搜索栏分享按钮
    - search.suggest # 搜索栏内容建议
plugins:
  # 内置插件
  - blog:
     blog_dir: blog
     blog_toc: true
     #archive_date_format: MMMM yyyy
  - search:
extra:
  analytics:
    provider: google
    property: G-E8P6LQT6ZG

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.blocks.tab
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true # 使用 Pygments 而不是 JavaScript 来渲染高亮
      line_spans: __span # 这对于高亮功能正常工作至关重要
      pygments_lang_class: true # 对于自定义注释标记的运行至关重要

  - pymdownx.blocks.html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - codehilite
  - footnotes
  - sane_lists
  - nl2br
  - markdown_checklist.extension
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys

nav:
  - index.md
  - Blog:
    - blog/index.md